# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks x
permalink:        pretty
relative_permalinks: false

# Setup
title:            HXA
tagline:          '@hexatomium blog'
description:      '@hexatomium blog' 
url:              http://hexatomium.github.io
baseurl:          /

author:
  name:           'Sven Faw'
  url:            https://twitter.com/hexatomium

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

theme: jekyll-theme-tactile